// Generated by https://quicktype.io

export interface ResultAlertas {
    ok:   boolean;
    msg:  string;
    resp: Resp[];
}

export interface Resp {
    id:              number;
    fecha:           string;
    hora:            string;
    conformidad:     null;
    id_administrado: number;
    id_tipo_alerta:  number;
    descripcion:     string;
    Administrado:    Administrado;
    TipoAlertum:     TipoAlertum;
}

export interface Administrado {
    id:        number;
    nombre:    string;
    apellido:  string;
    password:  string;
    dni:       string;
    tipo_area: number;
    area:      number;
}

export interface TipoAlertum {
    id:          number;
    descripcion: string;
    estado:      number;
}