// Generated by https://quicktype.io

export interface ResultArea {
    ok:   boolean;
    msg:  string;
    resp: Area;
}

export interface Area {
    id:                 number;
    nombre:             string;
    estado:             number;
    id_unidad_organica: number;
    UnidadOrganica:     UnidadOrganica;
}

export interface UnidadOrganica {
    id:        number;
    nombre:    string;
    estado:    number;
    id_organo: number;
    Organo:    Organo;
}

export interface Organo {
    id:      number;
    nombre:  string;
    estado:  number;
    id_sede: number;
    Sede:    Sede;
}

export interface Sede {
    id:     number;
    nombre: string;
    estado: number;
}
