// Generated by https://quicktype.io

export interface ResultAtenciones {
    ok:   boolean;
    msg:  string;
    resp: Atencion[];
}

export interface Atencion {
    id:   number;
    tipo: string;
}
