// Generated by https://quicktype.io

export interface LoginResponse {
    ok:    boolean;
    msg:   string;
    user:  User;
    token: string;
}

export interface User {
    id:       number;
    nombre:   string;
    apellido: string;
    usuario:  string;
    password: string;
    id_rol:   number;
    estado:   number;
    Rol:      Rol;
}

export interface Rol {
    id:     number;
    tipo:   string;
    estado: number;
}

export interface LoginData {
    usuario: string;
    password: string
}

export interface RegisterUser{
    nombre: string;
    apellido: string;
    password: string;
    usaurio: string;
    id_rol:string;
}