// Generated by https://quicktype.io

export interface ResultUnidadOrganica {
    ok:   boolean;
    msg:  string;
    resp: Unidad;
}

export interface Unidad {
    id:        number;
    nombre:    string;
    estado:    number;
    id_organo: number;
    anexo:string;
    Organo:    Organo;
}

export interface Organo {
    id:      number;
    nombre:  string;
    estado:  number;
    id_sede: number;
    Sede:    Sede;
}

export interface Sede {
    id:     number;
    nombre: string;
    estado: number;
}
