// Generated by https://quicktype.io

export interface ResultInformatico {
    ok:   boolean;
    msg:  string;
    resp: Informatico[];
}

export interface Informatico {
    id:       number;
    nombre:   string;
    apellido: string;
    usuario:  string;
    password: string;
    id_rol:   number;
    estado:   number;
}
